CREATE TABLE [dbo].[Addresses] (
    [ID]      BIGINT         IDENTITY (1, 1) NOT NULL,
    [Street1] NVARCHAR (MAX) NULL,
    [Street2] NVARCHAR (MAX) NULL,
    [City]    NVARCHAR (MAX) NULL,
    [State]   NVARCHAR (MAX) NULL,
    [Zip]     NVARCHAR (MAX) NULL,
    PRIMARY KEY CLUSTERED ([ID] ASC) WITH (ALLOW_PAGE_LOCKS = ON, ALLOW_ROW_LOCKS = ON, PAD_INDEX = OFF, IGNORE_DUP_KEY = OFF, STATISTICS_NORECOMPUTE = OFF)
);

