@searchTerm=some-search-term
@hostname=httpbin.org
# variable using another variable
@host=https://{{hostname}}
# variable using "dynamic variables"
@createdAt = {{$datetime iso8601}}
@fakeuser=fakeuser
@fakepwd=fakepwd

@searchTerm = some-search-term
@hostname = httpbin.org
# variable using another variable
@host = https://{{hostname}}
@name = Sayed
@phone = 111-222-3333
@sampleUrl = https://example.com



https://httpbin.org/get

###

https://httpbin.org/get

###


GET https://httpbin.org/get/{{searchTerm}}
###
GET https://httpbin.org/get?name=Sayed?&phone=111-222-3333
###
GET https://httpbin.org/get?name=Sayed?&phone=111-222-3333 HTTP/1.1
Date: Wed, 27 Apr 2023 07:28:00 GMT
###
GET https://httpbin.org/get?name=Sayed?&phone=111-222-3333
Cache-Control: max-age=604800
Age: 100
###
POST https://httpbin.org/post HTTP/1.1
Content-Type: application/json
Accept-Language: en-US,en;q=0.5

{
    "name": "sample",
    "time": "Wed, 21 Oct 2015 18:27:50 GMT",
    "someUrl":"https://example.com/sample"
}
###





GET {{host}}/anything HTTP/1.1
User-Agent: rest-client
Content-Type: application/json

###

GET https://example.com/topics/1 HTTP/1.1

###

GET https://httpbin.org/get?name=Sayed?&phone=111-222-3333 HTTP/1.1

###

POST https://httpbin.org/anything HTTP/1.1
content-type: application/json

{
    "name": "sample",
    "time": "Wed, 21 Oct 2015 18:27:50 GMT"
}

###

GET https://example.com/comments?page=2&pageSize=10
###

# request with a query string
GET https://httpbin.org/anything?page=2&pageSize=10
###

# request with a query string on multiple lines
GET https://httpbin.org/anything
    ?page=2
    &pageSize=10

###

# request with a query string on multiple lines and headers
GET https://httpbin.org/anything
    ?page=2
    &pageSize=10
User-Agent: rest-client
Accept-Language: en-GB,en-US;q=0.8,en;q=0.6,zh-CN;q=0.4
Content-Type: application/json

###

# request with a request body as HTML
POST https://httpbin.org/anything HTTP/1.1
Content-Type: application/xml
Authorization: token xxx

<request>
    <name>sample</name>
    <time>Wed, 21 Oct 2015 18:27:50 GMT</time>
</request>

###

# request with a request body that comes from a file, fullpath
POST https://httpbin.org/anything HTTP/1.1
Content-Type: application/xml
Authorization: token xxx

< C:\data\mycode\sayed-samples\http-files\demo.xml
###

# request with a request body that comes from a file, fullpath
#    note: \\ works as well as \
POST https://httpbin.org/anything HTTP/1.1
Content-Type: application/xml
Authorization: token xxx

< C:\\data\\mycode\\sayed-samples\\http-files\\demo.xml
###

# request with a request body that comes from a file, fullpath
#    note: / works as well as \ and \\
POST https://httpbin.org/anything HTTP/1.1
Content-Type: application/xml
Authorization: token xxx

< C:/data/mycode/sayed-samples/http-files/demo.xml
###

# request with a request body that comes from a file, relative path
POST https://httpbin.org/anything HTTP/1.1
Content-Type: application/xml
Authorization: token xxx

< ./demo.xml
###

# request with 
#    - a request body that comes from a file, relative path
#    - file has HTTP variables that need to be replaced
#       - indicated by <@ below.
# When the request is sent, notice that {{searchTerm}} is replaced
#    with the value that is defined at the top of this file.
POST https://httpbin.org/anything HTTP/1.1
Content-Type: application/xml
Authorization: token xxx

<@ ./demo.xml
###

# request with 
#    - a request body that comes from a file, relative path
#    - file has HTTP variables that need to be replaced
#       - indicated by <@ below.
#    - specifies file encoding (latin1 below)
# When the request is sent, notice that {{searchTerm}} is replaced
#    with the value that is defined at the top of this file.
POST https://httpbin.org/anything HTTP/1.1
Content-Type: application/xml
Authorization: token xxx

<@latin1 ./demo.xml
###

# reqeust with a basic JSON body
POST {{host}}/anything
Content-Type: application/json

{
  "identity": "some-value-here-json"
}

###

# request with a JSON object as the body

# sample put to update a template
PUT {{host}}/anything
Accept: application/json
Content-Type: application/json

{
  "author": "author-here",
  "name": "name here",
  "tags": {
    "additionalProp1": "ap1",
    "additionalProp2": "ap2",
    "additionalProp3": "ap3"
  },
  "classifications": [
    "console","web"
  ],
  "shortName": [
    "shortNameValue"
  ],
}
###

# request with a form URL encoded body
POST {{host}}/anything
Content-Type: application/x-www-form-urlencoded

identity=some-value-here

###

# request with a form URL encoded body across multiple lines
POST {{host}}/anything
Content-Type: application/x-www-form-urlencoded

name=foo
&password=bar

###

# @note Are you sure?
DELETE https://httpbin.org/anything

###

# request with content is a multipart/form-data.
# when this request is sent, the image is uploaded as well.
POST {{host}}/anything
Content-Type: multipart/form-data; boundary=----WebKitFormBoundary7MA4YWxkTrZu0gW

------WebKitFormBoundary7MA4YWxkTrZu0gW
Content-Disposition: form-data; name="text"

title
------WebKitFormBoundary7MA4YWxkTrZu0gW
Content-Disposition: form-data; name="image"; filename="img1.png"
Content-Type: image/png

< ./img1.png
------WebKitFormBoundary7MA4YWxkTrZu0gW--

###

# request that uses
GET https://httpbin.org/basic-auth/{{fakeuser}}/{{fakepwd}}


###

######
# Named reqeusts samples
######

# @name login
POST {{host}}/api/login HTTP/1.1
Content-Type: application/x-www-form-urlencoded

name=foo&password=bar

###
###

#################################
# Things that we don't currently support, and may never support
#################################

######
# Dynamic variables samples
######

# request using dynamic variables
POST https://httpbin.org/anything
Content-Type: application/json

{
    "request_id": "{{$guid}}",
    "updated_at": "{{$timestamp}}",
    "created_at": "{{$timestamp -1 d}}",
    "review_count": "{{$randomInt 5 200}}",
    "custom_date": "{{$datetime 'yyyy-MM-dd'}}",
    "local_custom_date": "{{$localDatetime 'yyyy-MM-dd'}}"
}

###

POST {{host}}/anything HTTP/1.1
Content-Type: application/json
Date: {{$datetime rfc1123}}

{
    "request_id": "{{$guid}}",
    "updated_at": "{{$timestamp}}",
    "created_at": "{{$timestamp -1 d}}",
    "review_count": "{{$randomInt 5 200}}",
    "custom_date": "{{$datetime 'yyyy-MM-dd'}}",
    "local_custom_date": "{{$localDatetime 'yyyy-MM-dd'}}"
}

###

######
# GraphQL samples
######
POST https://api.github.com/graphql
Content-Type: application/json
Authorization: Bearer xxx
X-REQUEST-TYPE: GraphQL

query ($name: String!, $owner: String!) {
  repository(name: $name, owner: $owner) {
    name
    fullName: nameWithOwner
    description
    diskUsage
    forkCount
    stargazers(first: 5) {
        totalCount
        nodes {
            login
            name
        }
    }
    watchers {
        totalCount
    }
  }
}

{
    "name": "vscode-restclient",
    "owner": "Huachao"
}

###

######
# Curl samples
######

# curl request on one line
curl -X 'POST' 'https://httpbin.org/anything' -H 'accept: application/json' -H 'Content-Type: application/json' -d '"id1-goes-here"'

###

# curl request over multiple lines
curl -X 'POST' 'https://httpbin.org/anything' 
-H 'accept: application/json' 
-H 'Content-Type: application/json' 
-d '"id2-goes-here"'
###
# curl request over multiple lines
#  notice how there is two -h on a single line
curl -X 'POST' 'https://httpbin.org/anything' 
-H 'accept: application/json' -H 'Content-Type: application/json' 
-d '"id3-goes-here"'
###
curl -X POST -F "field=value1" "https://httpbin.org/anything"
{
  "author": "author-here",
  "name": "name here",
  "tags":{
    "additionalProp1": "ap1",
    "additionalProp2": "ap2",
    "additionalProp3": "ap3"
  },
  "classifications": [
    "console","web"
  ],
  "shortName": [
    "shortNameValue"
  ]
}

###

# curl command taking text from a file as the
#    @filename is the syntax
curl -X POST -d @postme.json "http://httpbin.org/post"

###

# curl command taking text from a file as the
#    @filename is a relative path here
curl -X POST -d @./postme.json "http://httpbin.org/post"

###

# curl command taking text from a file as the
#    @filename is a full path here
curl -X POST -d @C:\\data\\mycode\\sayed-samples\\http-files\\postme.json "http://httpbin.org/post"
###

# curl command taking text from a file as the
#    @filename is a full path here, using \ instead of \\
curl -X POST -d @C:/data/mycode/sayed-samples/http-files/postme.json "http://httpbin.org/post"
###


GET https://httpbin.org/anything?page=2&pageSize=10


###
GET https://dotnetnew-api.azurewebsites.net/api/search/winforms
###


POST https://httpbin.org/anything HTTP/1.1
Content-Type: application/x-www-form-urlencoded

name=foo
&password=bar

###
GET https://management.azure.com/subscriptions/{{subscriptionId}}/{{query}}?api-version={{apiversion}}
Authorization: {{$aadToken}}
Accept: application/json
###