
delete from States
Insert into States(StateCode,Name) values('AL','Alabama')
Insert into States(StateCode,Name) values('AK','Alaska')
Insert into States(StateCode,Name) values('AZ','Arizona')
Insert into States(StateCode,Name) values('AR','Arkansas')
Insert into States(StateCode,Name) values('CA','California')
Insert into States(StateCode,Name) values('CO','Colorado')
Insert into States(StateCode,Name) values('CT','Connecticut')
Insert into States(StateCode,Name) values('DE','Delaware')
Insert into States(StateCode,Name) values('DC','District of Columbia')
Insert into States(StateCode,Name) values('FL','Florida')
Insert into States(StateCode,Name) values('GA','Georgia')
Insert into States(StateCode,Name) values('HI','Hawaii')
Insert into States(StateCode,Name) values('ID','Idaho')
Insert into States(StateCode,Name) values('IL','Illinois')
Insert into States(StateCode,Name) values('IN','Indiana')
Insert into States(StateCode,Name) values('IA','Iowa')
Insert into States(StateCode,Name) values('KS','Kansas')
Insert into States(StateCode,Name) values('KY','Kentucky')
Insert into States(StateCode,Name) values('LA','Louisiana')
Insert into States(StateCode,Name) values('ME','Maine')
Insert into States(StateCode,Name) values('MT','Montana')
Insert into States(StateCode,Name) values('NE','Nebraska')
Insert into States(StateCode,Name) values('NV','Nevada')
Insert into States(StateCode,Name) values('NH','New Hampshire')
Insert into States(StateCode,Name) values('NJ','New Jersey')
Insert into States(StateCode,Name) values('NM','New Mexico')
Insert into States(StateCode,Name) values('NY','New York')
Insert into States(StateCode,Name) values('NC','North Carolina')
Insert into States(StateCode,Name) values('ND','North Dakota')
Insert into States(StateCode,Name) values('OH','Ohio')
Insert into States(StateCode,Name) values('OK','Oklahoma')
Insert into States(StateCode,Name) values('OR','Oregon')
Insert into States(StateCode,Name) values('MD','Maryland')
Insert into States(StateCode,Name) values('MA','Massachusetts')
Insert into States(StateCode,Name) values('MI','Michigan')
Insert into States(StateCode,Name) values('MN','Minnesota')
Insert into States(StateCode,Name) values('MS','Mississippi')
Insert into States(StateCode,Name) values('MO','Missouri')
Insert into States(StateCode,Name) values('PA','Pennsylvania')
Insert into States(StateCode,Name) values('RI','Rhode Island')
Insert into States(StateCode,Name) values('SC','South Carolina')
Insert into States(StateCode,Name) values('SD','South Dakota')
Insert into States(StateCode,Name) values('TN','Tennessee')
Insert into States(StateCode,Name) values('TX','Texas')
Insert into States(StateCode,Name) values('UT','Utah')
Insert into States(StateCode,Name) values('VT','Vermont')
Insert into States(StateCode,Name) values('VA','Virginia')
Insert into States(StateCode,Name) values('WA','Washington')
Insert into States(StateCode,Name) values('WV','West Virginia')
Insert into States(StateCode,Name) values('WI','Wisconsin')
Insert into States(StateCode,Name) values('WY','Wyoming')

delete from [Contacts]
delete from [Addresses]
GO

SET IDENTITY_INSERT [Addresses] ON
INSERT INTO [Addresses]([ID],[Street1],[Street2],[City],[State],[Zip])VALUES(1,'Street 1 - 01','Street 2 - 01','City 01','WA','98102')
INSERT INTO [Addresses]([ID],[Street1],[Street2],[City],[State],[Zip])VALUES(2,'Street 1 - 02','Street 2 - 02','City 02','WA','98102')
INSERT INTO [Addresses]([ID],[Street1],[Street2],[City],[State],[Zip])VALUES(3,'Street 1 - 03','Street 2 - 03','City 03','WA','98102')
INSERT INTO [Addresses]([ID],[Street1],[Street2],[City],[State],[Zip])VALUES(4,'Street 1 - 04','Street 2 - 04','City 04','WA','98102')
INSERT INTO [Addresses]([ID],[Street1],[Street2],[City],[State],[Zip])VALUES(5,'Street 1 - 05','Street 2 - 05','City 05','WA','98102')
INSERT INTO [Addresses]([ID],[Street1],[Street2],[City],[State],[Zip])VALUES(6,'Street 1 - 06','Street 2 - 06','City 06','WA','98102')
INSERT INTO [Addresses]([ID],[Street1],[Street2],[City],[State],[Zip])VALUES(7,'Street 1 - 07','Street 2 - 07','City 07','WA','98102')
INSERT INTO [Addresses]([ID],[Street1],[Street2],[City],[State],[Zip])VALUES(8,'Street 1 - 08','Street 2 - 08','City 08','WA','98102')
INSERT INTO [Addresses]([ID],[Street1],[Street2],[City],[State],[Zip])VALUES(9,'Street 1 - 09','Street 2 - 09','City 09','WA','98102')
INSERT INTO [Addresses]([ID],[Street1],[Street2],[City],[State],[Zip])VALUES(10,'Street 1 - 10','Street 2 - 10','City 10','WA','98102')
INSERT INTO [Addresses]([ID],[Street1],[Street2],[City],[State],[Zip])VALUES(11,'Street 1 - 11','Street 2 - 11','City 11','WA','98102')
INSERT INTO [Addresses]([ID],[Street1],[Street2],[City],[State],[Zip])VALUES(12,'Street 1 - 12','Street 2 - 12','City 12','WA','98102')
INSERT INTO [Addresses]([ID],[Street1],[Street2],[City],[State],[Zip])VALUES(13,'Street 1 - 13','Street 2 - 13','City 13','WA','98102')
INSERT INTO [Addresses]([ID],[Street1],[Street2],[City],[State],[Zip])VALUES(14,'Street 1 - 14','Street 2 - 14','City 14','WA','98102')
INSERT INTO [Addresses]([ID],[Street1],[Street2],[City],[State],[Zip])VALUES(15,'Street 1 - 15','Street 2 - 15','City 15','WA','98102')
INSERT INTO [Addresses]([ID],[Street1],[Street2],[City],[State],[Zip])VALUES(16,'Street 1 - 16','Street 2 - 16','City 16','WA','98102')
INSERT INTO [Addresses]([ID],[Street1],[Street2],[City],[State],[Zip])VALUES(17,'Street 1 - 17','Street 2 - 17','City 17','WA','98102')
INSERT INTO [Addresses]([ID],[Street1],[Street2],[City],[State],[Zip])VALUES(18,'Street 1 - 18','Street 2 - 18','City 18','WA','98102')
INSERT INTO [Addresses]([ID],[Street1],[Street2],[City],[State],[Zip])VALUES(19,'Street 1 - 19','Street 2 - 19','City 19','WA','98102')
INSERT INTO [Addresses]([ID],[Street1],[Street2],[City],[State],[Zip])VALUES(20,'Street 1 - 20','Street 2 - 20','City 20','WA','98102')
INSERT INTO [Addresses]([ID],[Street1],[Street2],[City],[State],[Zip])VALUES(21,'Street 1 - 21','Street 2 - 21','City 21','WA','98102')
INSERT INTO [Addresses]([ID],[Street1],[Street2],[City],[State],[Zip])VALUES(22,'Street 1 - 22','Street 2 - 22','City 22','WA','98102')
INSERT INTO [Addresses]([ID],[Street1],[Street2],[City],[State],[Zip])VALUES(23,'Street 1 - 23','Street 2 - 23','City 23','WA','98102')
INSERT INTO [Addresses]([ID],[Street1],[Street2],[City],[State],[Zip])VALUES(24,'Street 1 - 24','Street 2 - 24','City 24','WA','98102')
INSERT INTO [Addresses]([ID],[Street1],[Street2],[City],[State],[Zip])VALUES(25,'Street 1 - 25','Street 2 - 25','City 25','WA','98102')
SET IDENTITY_INSERT [Addresses] OFF

GO

SET IDENTITY_INSERT [Contacts] ON
INSERT INTO [Contacts]([FirstName],[LastName],[Phone],[Email],[ID],[Address_ID])VALUES(' Kim','Abercrombie','111-222-3333',' Kim.Abercrombie@contoso.com','1',1)
INSERT INTO [Contacts]([FirstName],[LastName],[Phone],[Email],[ID],[Address_ID])VALUES(' Hazem','Abolrous','111-222-3334',' Hazem.Abolrous@contoso.com','2',2)
INSERT INTO [Contacts]([FirstName],[LastName],[Phone],[Email],[ID],[Address_ID])VALUES(' Luka','Abrus','111-222-3335',' Luka.Abrus@contoso.com','3',3)
INSERT INTO [Contacts]([FirstName],[LastName],[Phone],[Email],[ID],[Address_ID])VALUES(' Ahmad','Abu-Dayah','111-222-3336',' Ahmad.Abu-Dayah@contoso.com','4',4)
INSERT INTO [Contacts]([FirstName],[LastName],[Phone],[Email],[ID],[Address_ID])VALUES(' Humberto','Acevedo','111-222-3337',' Humberto.Acevedo@contoso.com','5',5)
INSERT INTO [Contacts]([FirstName],[LastName],[Phone],[Email],[ID],[Address_ID])VALUES(' Gustavo','Achong','111-222-3338',' Gustavo.Achong@contoso.com','6',6)
INSERT INTO [Contacts]([FirstName],[LastName],[Phone],[Email],[ID],[Address_ID])VALUES(' Pilar','Ackerman','111-222-3339',' Pilar.Ackerman@contoso.com','7',7)
INSERT INTO [Contacts]([FirstName],[LastName],[Phone],[Email],[ID],[Address_ID])VALUES(' Gudmundur','Adalsteinsson','111-222-3340',' Gudmundur.Adalsteinsson@contoso.com','8',8)
INSERT INTO [Contacts]([FirstName],[LastName],[Phone],[Email],[ID],[Address_ID])VALUES(' Terry','Adams','111-222-3341',' Terry.Adams@contoso.com','9',9)
INSERT INTO [Contacts]([FirstName],[LastName],[Phone],[Email],[ID],[Address_ID])VALUES(' Michael','Affronti','111-222-3342',' Michael.Affronti@contoso.com','10',10)
INSERT INTO [Contacts]([FirstName],[LastName],[Phone],[Email],[ID],[Address_ID])VALUES(' Manoj','Agarwal','111-222-3343',' Manoj.Agarwal@contoso.com','11',11)
INSERT INTO [Contacts]([FirstName],[LastName],[Phone],[Email],[ID],[Address_ID])VALUES(' Nupur','Agarwal','111-222-3344',' Nupur.Agarwal@contoso.com','12',12)
INSERT INTO [Contacts]([FirstName],[LastName],[Phone],[Email],[ID],[Address_ID])VALUES(' David','Ahs','111-222-3345',' David.Ahs@contoso.com','13',13)
INSERT INTO [Contacts]([FirstName],[LastName],[Phone],[Email],[ID],[Address_ID])VALUES(' Hatim','Aiad','111-222-3346',' Hatim.Aiad@contoso.com','14',14)
INSERT INTO [Contacts]([FirstName],[LastName],[Phone],[Email],[ID],[Address_ID])VALUES(' François','Ajenstat','111-222-3347',' François.Ajenstat@contoso.com','15',15)
INSERT INTO [Contacts]([FirstName],[LastName],[Phone],[Email],[ID],[Address_ID])VALUES(' Kim','Akers','111-222-3348',' Kim.Akers@contoso.com','16',16)
INSERT INTO [Contacts]([FirstName],[LastName],[Phone],[Email],[ID],[Address_ID])VALUES(' Cigdem','Akin','111-222-3349',' Cigdem.Akin@contoso.com','17',17)
INSERT INTO [Contacts]([FirstName],[LastName],[Phone],[Email],[ID],[Address_ID])VALUES(' Kweku','Ako-Adjei','111-222-3350',' Kweku.Ako-Adjei@contoso.com','18',18)
INSERT INTO [Contacts]([FirstName],[LastName],[Phone],[Email],[ID],[Address_ID])VALUES(' Greg','Akselrod','111-222-3351',' Greg.Akselrod@contoso.com','19',19)
INSERT INTO [Contacts]([FirstName],[LastName],[Phone],[Email],[ID],[Address_ID])VALUES(' Amy E.','Alberts','111-222-3352',' Amy E..Alberts@contoso.com','20',20)
INSERT INTO [Contacts]([FirstName],[LastName],[Phone],[Email],[ID],[Address_ID])VALUES(' Brian T.','Albrecht','111-222-3353',' Brian T..Albrecht@contoso.com','21',21)
INSERT INTO [Contacts]([FirstName],[LastName],[Phone],[Email],[ID],[Address_ID])VALUES(' David','Alexander','111-222-3354',' David.Alexander@contoso.com','22',22)
INSERT INTO [Contacts]([FirstName],[LastName],[Phone],[Email],[ID],[Address_ID])VALUES(' Michael','Alexander','111-222-3355',' Michael.Alexander@contoso.com','23',23)
INSERT INTO [Contacts]([FirstName],[LastName],[Phone],[Email],[ID],[Address_ID])VALUES(' Michelle','Alexander','111-222-3356',' Michelle.Alexander@contoso.com','24',24)
INSERT INTO [Contacts]([FirstName],[LastName],[Phone],[Email],[ID],[Address_ID])VALUES(' Diliana','Alexieva-Bosseva','111-222-3357',' Diliana.Alexieva-Bosseva@contoso.com','25',25)

SET IDENTITY_INSERT [Contacts] OFF
GO